### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by plskeggs** [ElektorLabs/Arduino#3]
This page: https://github.com/ElektorLabs/Arduino references:
https://github.com/ElektorLabs/Arduino/releases/download/v1.0.0/package_elektor_uno_r4_1_8_x_index.json 
but it should instead be: 
https://github.com/ElektorLabs/Arduino/releases/download/v1.0.1/package_elektor_uno_r4_1_8_x_index.json.

Further, the package_elektor_uno_r4_1_8_x_index.json itself has a broken link.  

It references: https://github.com/ElektorLabs/Arduino/releases/download/v1.0.0/elektor-uno-r4-1.8.x-1.0.0.zip
but it should instead be:
https://github.com/ElektorLabs/Arduino/releases/download/v1.0.1/elektor-uno-r4-1.8.x-1.0.0.zip

**Comment by elektor-labs** [comment]
Thank you, has been corrected.
